from pydantic import BaseModel, Field
from typing import Dict, List, Optional

class MacroFactorShock(BaseModel):
    """Defines a shock (change) to a single macroeconomic factor."""
    factor_name: str = Field(..., description="Name of the macro factor (e.g., 'GDP_Growth', 'Interest_Rate').")
    shock_value: float = Field(..., description="The absolute or relative change applied to the factor.")
    unit: str = Field(default="pct_points", description="Unit of shock: 'pct_points', 'relative_change', or 'absolute'.")

class ScenarioInput(BaseModel):
    """The structured input for a financial stress test scenario, generated by the SLM."""
    scenario_name: str = Field(..., description="A short, descriptive name for the stress scenario (e.g., 'Inverted Yield Curve Shock').")
    narrative: str = Field(..., description="A detailed narrative explaining the economic drivers and assumptions.")
    shocks: List[MacroFactorShock] = Field(..., description="List of specific macro factor shocks to apply to the model.")
    portfolio_segment: str = Field(default="Retail_Credit", description="The portfolio segment being tested (e.g., 'Corporate_Bonds', 'Retail_Credit').")
    time_horizon_months: int = Field(default=12, description="The time horizon for the stress test in months.")

class RiskMetric(BaseModel):
    """Defines a calculated risk metric for the result."""
    metric_name: str = Field(..., description="Name of the risk metric (e.g., 'Expected_Loss', 'VaR_99').")
    value: float = Field(..., description="The calculated value of the metric under stress.")
    unit: str = Field(default="USD_Million", description="The unit of the value.")
    baseline_value: float = Field(default=0.0, description="The expected baseline value for comparison.")

class RiskOutput(BaseModel):
    """The final structured output from the ML engine."""
    scenario_id: str = Field(..., description="Unique ID for the scenario run.")
    status: str = Field(..., description="Status of the calculation ('Success', 'Failure').")
    description: str = Field(..., description="Summary of the model run.")
    net_impact: float = Field(..., description="The total calculated negative impact (e.g., total loss).")
    metrics: List[RiskMetric] = Field(..., description="List of specific risk metrics calculated.")
    pnl_simulation_path: List[float] = Field(default=[], description="Simulated PnL over the time horizon for charting.")
    
    # Optional field for model explanation (XGBoost Feature Importance)
    feature_impact: Dict[str, float] = Field(default={}, description="The model's internal feature importance for the prediction.")